// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCObDstYyjKpOTpoxN_UM66g8z1YtHotA',
    appId: '1:410819832475:web:6afc3194c851cd9f6df43e',
    messagingSenderId: '410819832475',
    projectId: 'budgetin-7e8cf',
    authDomain: 'budgetin-7e8cf.firebaseapp.com',
    storageBucket: 'budgetin-7e8cf.firebasestorage.app',
    measurementId: 'G-2CTZML87DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Qon6TcUQtgaAi6dVz8SyLlsVWLJdgl4',
    appId: '1:410819832475:android:c1ecbd1f613613a86df43e',
    messagingSenderId: '410819832475',
    projectId: 'budgetin-7e8cf',
    storageBucket: 'budgetin-7e8cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpLGnXVvhNM9Y55tP-pngC9LctY9m1u0',
    appId: '1:410819832475:ios:916c547d47164d486df43e',
    messagingSenderId: '410819832475',
    projectId: 'budgetin-7e8cf',
    storageBucket: 'budgetin-7e8cf.firebasestorage.app',
    iosBundleId: 'com.example.budgetinFrontend',
  );
}
